version: '3.8'

services:
  backend:
    build: ./backend
    restart: always
    environment:
      - DATABASE_URL=mysql+pymysql://nextnrgie_user:Paki7stan8%23paki@mysql:3306/nextnrgie_prod
      - ENVIRONMENT=production
      - SECRET_KEY=your-secret-key-here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - CORS_ORIGINS=["https://nextnrgie.fr", "https://www.nextnrgie.fr", "http://localhost:3000", "http://82.29.172.241:3000"]
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    networks:
      - nextnrgie-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - nextnrgie-network

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Paki7stan8#paki
      MYSQL_DATABASE: nextnrgie_prod
      MYSQL_USER: nextnrgie_user
      MYSQL_PASSWORD: Paki7stan8#paki
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nextnrgie-network

networks:
  nextnrgie-network:
    driver: bridge

volumes:
  mysql_data: