services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://nextnrgie_user:Paki7stan8#paki@mysql:3306/nextnrgie_prod
      - ENVIRONMENT=production
      - SECRET_KEY=your-secret-key-here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - CORS_ORIGINS=["https://nextnrgie.fr", "https://www.nextnrgie.fr"]
    depends_on:
      - mysql
    networks:
      - nextnrgie-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Paki7stan8#paki
      MYSQL_DATABASE: nextnrgie_prod
      MYSQL_USER: nextnrgie_user
      MYSQL_PASSWORD: Paki7stan8#paki
    ports:
      - "3307:3306"  # Changed from 3306 to 3307 to avoid port conflict
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nextnrgie-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=https://nextnrgie.fr/api
    depends_on:
      - backend
    networks:
      - nextnrgie-network

volumes:
  mysql_data:

networks:
  nextnrgie-network:
    driver: bridge
