"""Add contract_details table

Revision ID: 276cd7874713
Revises: 717629592bf4
Create Date: 2025-07-12 21:30:10.973588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '276cd7874713'
down_revision: Union[str, None] = '717629592bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Get database connection
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Check if table exists before dropping
    if 'contract_items' in inspector.get_table_names():
        op.drop_table('contract_items')
        
    # Create contract_details table if it doesn't exist
    if 'contract_details' not in inspector.get_table_names():
        op.create_table(
            'contract_details',
            sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
            sa.Column('contract_id', sa.Integer(), sa.ForeignKey('contracts.id'), nullable=False),
            sa.Column('description', sa.String(255), nullable=False),
            sa.Column('qty', sa.Integer(), nullable=False),
            sa.Column('qty_unit', sa.String(20), server_default='unite'),
            sa.Column('unit_price', sa.Float(), nullable=False),
            sa.Column('tva', sa.Float(), nullable=False),
            sa.Column('total_ht', sa.Float(), nullable=False),
            sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP')),
            sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_items',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('contract_id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('qty', sa.INTEGER(), nullable=False),
    sa.Column('unit_price', sa.FLOAT(), nullable=False),
    sa.Column('tva', sa.FLOAT(), nullable=False),
    sa.Column('total_ht', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
