name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOMAIN: nextnrgie.fr
  API_URL: https://nextnrgie.fr/api
  BASE_URL: https://nextnrgie.fr

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Paki7stan8#paki
          MYSQL_DATABASE: nextnrgie_prod
          MYSQL_USER: nextnrgie_user
          MYSQL_PASSWORD: Paki7stan8#paki
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        # Install backend requirements first
        if [ -f backend/requirements.txt ]; then 
          pip install -r backend/requirements.txt; 
        fi
        # Install test dependencies
        pip install pytest pytest-cov python-dotenv
        # Install the package in development mode
        if [ -f setup.py ]; then
          pip install -e .
        fi
    
    - name: Run tests
      env:
        DATABASE_URL: mysql+pymysql://nextnrgie_user:Paki7stan8%23paki@127.0.0.1:3306/nextnrgie_prod
        ENVIRONMENT: test
      run: |
        # Run tests in the backend directory
        cd backend
        python -m pytest test_*.py -v || echo "Tests completed with status code $?"
        
        # Run specific test files in the root
        cd ..
        if [ -f test_db.py ]; then
          python -m pytest test_db.py -v || echo "test_db.py completed with status code $?"
        fi
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push backend
      uses: docker/build-push-action@v6
      with:
        context: ./backend
        file: ./backend/Dockerfile.prod
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/nextnrgie-backend:latest
    
    - name: Build and push frontend
      uses: docker/build-push-action@v6
      with:
        context: ./frontend
        file: ./frontend/Dockerfile.prod
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/nextnrgie-frontend:latest
        build-args: |
          REACT_APP_API_URL=${{ env.API_URL }}
          REACT_APP_BASE_URL=${{ env.BASE_URL }}

    - name: Check if mysql-init exists
      id: check-mysql-init
      run: |
        if [ -d "mysql-init" ]; then
          echo "mysql-init directory exists"
          echo "exists=true" >> $GITHUB_OUTPUT
          ls -la mysql-init/
        else
          echo "mysql-init directory not found"
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Ensure target directory exists on server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USER }}
        key: ${{ secrets.PROD_SSH_KEY }}
        timeout: 2m
        command_timeout: 20m
        script: |
          mkdir -p /opt/nextnrgie
          mkdir -p /opt/nextnrgie/mysql-init

    - name: Copy compose file to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USER }}
        key: ${{ secrets.PROD_SSH_KEY }}
        source: "docker-compose.prod.yml"
        target: "/opt/nextnrgie/"

    - name: Copy mysql-init to server if exists
      if: steps.check-mysql-init.outputs.exists == 'true'
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USER }}
        key: ${{ secrets.PROD_SSH_KEY }}
        source: "mysql-init/"
        target: "/opt/nextnrgie/"
        strip_components: 1  # This will remove the mysql-init/ from the target path
      continue-on-error: true

    - name: Create/update env file on server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USER }}
        key: ${{ secrets.PROD_SSH_KEY }}
        timeout: 2m
        command_timeout: 20m
        script: |
          set -e
          mkdir -p /opt/nextnrgie
          cat >/opt/nextnrgie/.env.prod <<'EOF'
          # Backend
          DATABASE_URL=mysql+pymysql://nextnrgie:Farhan113@mysql:3306/nextnrgie
          SECRET_KEY=${{ secrets.BACKEND_SECRET_KEY }}
          ENVIRONMENT=production
          
          # MySQL
          MYSQL_ROOT_PASSWORD=Farhan113
          MYSQL_DATABASE=nextnrgie
          MYSQL_USER=nextnrgie
          MYSQL_PASSWORD=Farhan113
          
          # Frontend
          REACT_APP_API_URL=${{ env.API_URL }}
          REACT_APP_BASE_URL=${{ env.BASE_URL }}
          
          # Nginx
          VIRTUAL_HOST=${{ env.DOMAIN }}
          VIRTUAL_PORT=80
          LETSENCRYPT_HOST=${{ env.DOMAIN }}
          LETSENCRYPT_EMAIL=admin@${{ env.DOMAIN }}
          EOF

    - name: Deploy with docker compose
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USER }}
        key: ${{ secrets.PROD_SSH_KEY }}
        timeout: 5m
        command_timeout: 30m
        script: |
          set -e
          cd /opt/nextnrgie
          
          # Export required environment variables
          export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          
          # Stop and remove existing containers
          echo "Stopping and removing existing containers..."
          docker compose -f docker-compose.prod.yml down --remove-orphans || true
          
          # Pull the latest images
          echo "Pulling latest images..."
          docker compose -f docker-compose.prod.yml pull
          
          # Start the services
          echo "Starting services..."
          docker compose -f docker-compose.prod.yml up -d
          
          # Check service status
          echo "Checking service status..."
          docker ps
          
          # Verify Nginx is running
          echo "Verifying Nginx is running..."
          sleep 10  # Give services time to start
          docker logs nextnrgie-nginx-1
          
          # Check frontend logs
          echo "Checking frontend logs..."
          docker logs nextnrgie-frontend-1 || true
          
          # Check backend logs
          echo "Checking backend logs..."
          docker logs nextnrgie-backend-1 || true
          
          # Verify services are accessible
          echo "Verifying services are accessible..."
          curl -I http://localhost || true